

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pk-az-managed-disc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed premium
  resources: 
    requests:
      storage: 1 Gib


---
apiVersion: v1
kind: pod
metadata: 
  name: mysql-pvc
spec: 
  containers:
    - name: mysqlDB
      image: mysql:latest
      ports:
        - conatainerPorts: 3306  
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: rootroot
       - name: MYSQL_DATABASE
         value: my-root
       - name: MYSQL_USER
         value: prathamesh
       - name: MYSQL_PASSWORD    
         value: prathamesh
  VolumeMount:
    name: mysqlvolume
    mountpath: /var/lib/myql
volumes:
  -name: mysqlvolume
  persistentVolumeClaim:
    claimName: pk-az-managed-disc
 



          
         
          
      